### PR TITLE
Fix/503

### LINKED ISSUE #503: Enable extending VCL from Magento modules
### The problem we are trying to solve

We have quite a lot of projects on Magento Cloud and therefore using Fastly. These projects have some common functionality that would be nice to have as a separate packages (to support them only once). It’s all fun and games until some of these shared functionalities need to manage VCL code. 

For example, we are trying to build a simple module that handles redirects: 

* It adds a toggle in admin whether to redirect www.domain.name to domain.name, redirect domain.name to www.domain.name or do nothing;
* It adds a toggle to redirect https://domain.name/PrOdUcTs/sku to https://domain.name/products/sku;
* It adds a dictionary of 301 redirects.

Obvious, these features require some VCL management. Fastly module provides a way to manage VCL snippets from Magento Admin, which is awesome, but does not fully solve our problem, because the module kinda loses its purpose of being plug-n-play thing (one needs to remember to go to Admin and copy/paste these VCL snippets into Admin).

What we do now is we have an AFTER plugin that hooks into \Fastly\Cdn\Model\Config::getCustomSnippets and loads other modules VCL snippets (modules can register an implementation of special interface in a composite). This allows us to easily ADD custom snippets before they get uploaded.

### But… how do I delete custom snippet?

Well, what if I first enabled “www to no www” redirect, but then I decided I want it vice-versa? In this case, extension must delete one VCL and install another one, but implementation of `getCustomSnippets` doesn’t call for “snippets to delete”, it calls only for “snippets to add”.  

I have several options (one worse than the other)

###    Merge VCL snippets and build-in feature flags  
  
```vcl
   declare local var.www_redirect_strategy STRING;
set var.www_redirect_strategy = “####SOME_MAGIC_REPLACEMENT####”;

If (var.www_redirect_strategy == “from_www”) {
    // handle from www redirect
} else if (var.www_redirect_strategy == “to_www”) {     
    // handle to www redirect 
} 
```

  Yes, it allows us to avoid deleting VCL snippet _in this case_ by making one snippet out of two and making it much more clunky.

###  Extend a plugin so that it allows modules to delete snippets

My main concern here is it goes way beyond `Fastly\Cdn\Model\Config::getCustomSnippets` functionality (it not only provides a list of custom snippets but deletes unused snippets now).

Having an event after handling built-in custom snippets functionality in `\Fastly\Cdn\Controller\Adminhtml\FastlyCdn\Vcl\Upload::execute` would really help me :)  

```php
foreach ($customSnippets as $key => $value) {
}

  $this->eventManager->dispatch('fastly_custom_snippets', [     
      'api' => $this->api,
    'version' => $clone
]);
```

In this case, even subscriber would be able to call other modules to build an unit of work to be done in order to sync "module VCL snippets"

So, yeah, thanks for reading this :) I’d like to hear your concerns about the way I’m going and my suggestion.

### PR DESCRIPTION
**Pull request by dpotkoc**
Improvement for snippets. 
On upload vcl action (from Magento admin section), added logic for fetch and delete all not existing custom snippets which name start with prefix "**magentomodule_**"
this fix close #503

### CODE REVIEW

File: Controller/Adminhtml/FastlyCdn/Vcl/Upload.php [hunk 1]
```diff
@@ -154,7 +152,10 @@ public function execute()
             $read = $this->filesystem->getDirectoryRead(DirectoryList::VAR_DIR);
             $customSnippetPath = $read->getAbsolutePath(Config::CUSTOM_SNIPPET_PATH);
             $customSnippets = $this->config->getCustomSnippets($customSnippetPath);
+            //$customSnippets['recv_200_Proba'] = 'set req.http.proba = "1";';
```
Comment (bbutkovic) [inline Controller/Adminhtml/FastlyCdn/Vcl/Upload.php:155]: remove this

**Review by bbutkovic — CHANGES_REQUESTED** [review]
